
title: "Mount Adams Challenge"
meta_desc: "The Mount Adams challenge is an entirely informal event, to be undertaken by individuals who are looking for a personal challenge, and purely for their own satisfaction."
url: "https://www.mountadamschallenge.org"
