backend:
  name: git-gateway
  branch: main
local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
media_folder: "/src/assets/images/uploads/"
public_folder: "/assets/images/uploads/"
site_url: "https://www.mountadamschallenge.org/"
display_url: "https://www.mountadamschallenge.org"
logo_url: "/assets/images/logo-admin.png"
collections:

  - name: "results"
    label: "Results"
    label_singular: "Result"
    folder: "src/results/"
    identifier_field: "name"
    slug: "{{run_date}}-{{name}}"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    editor:
      preview: false
    extension: "md"
    format: "toml-frontmatter"
    frontmatter_delimiter: ['---toml', '---']
    summary: "{{run_date | date('YYYY-MM-DD')}} • {{name}} • [{{run_duration}}]"
    description: "Results for each participant of the MAC. Reports filed here appear in the 'Reports' section of the site."
    fields: # The fields for each document, usually in front matter
      - label: Runner's Name
        name: name
        widget: string
        hint: 'Runner''s first then last name (e.g., ''Doug Mayer'')'
        required: true
      - label: Run Date
        name: run_date
        widget: date
        date_format: "YYYY-MM-DD"
        format: "YYYY-MM-DD"
        picker_utc: true
        default: ''
        hint: Date of attempt on the Mount Adams Challenge
        required: true
      - label: Runner's Time
        name: run_duration
        widget: string
        hint: Runner's run time. Format should be 'H:MM:SS'
        required: true
      - label: Other Runners?
        name: other_runners
        widget: array
        hint: Did this runner have MAC accomplices? If so, list names separated by commas (e.g, "Doug Mayer, Steve Bailey, Jacques Cousteau")
        required: false
      - label: Report
        name: body
        widget: markdown
        minimal: false
        buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
        editor_components: ['image']
        modes: [rich_text]
        required: false
        hint: If there is a report, paste it in here!
      - label: Year
        name: year
        widget: hidden
    sortable_fields:
      - run_date
      - name
      - run_duration
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}

  - name: "segments" # Used in routes, e.g., /admin/collections/blog
    identifier_field: "name"
    label: "Route Segments" # Used in the UI
    label_singular: "Segment"
    folder: "src/segments/"
    extension: "md"
    slug: "{{field.order}}-{{field.name}}"
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    editor:
      preview: false
    summary: "{{order}} • {{name}}"
    description: "Make sure runners stay on course with good directions!"
    fields:
      - label: Order
        name: order
        widget: number
        hint: The order of this segment in relation to the start at Appalachia.
      - label: Segment Name
        name: name
        widget: string
        hint: "Trail name"
        required: true
      - label: Segment Stats
        name: stats
        widget: array
        hint: "Segment stats shorthand: Distance, Grade, Elevation Change."
        required: true
      - label: Segment Description
        name: body
        widget: markdown
        minimal: true
        buttons: ['bold', 'italic', 'link']
        editor_components: []
        modes: [rich_text]
        required: true
        hint: Short description of the segment.
    sortable_fields: ['order']


  - name: "site_info"
    label: "Site Info"
    description: "Sitewide info goes here."
    files:
      - label: "Meta"
        name: "meta"
        delete: false
        editor:
          preview: false
        file: "src/_data/site_meta.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string", hint: "Text that appears in search results, when shared on social media, etc."}
          - {label: "Site Description", name: "description", widget: "text", hint: "Text that appears below title in search results and sometimes on social media. Google truncates around 160 characters.", pattern: ['.{1,160}', "Should be 160 characters or less."]}
          - {label: "Site Url", name: "url", widget: "string"}
