backend:
  name: git-gateway
  branch: main
local_backend:
  url: http://localhost:4567/api/v1
media_folder: "src/images/upload"
public_folder: "/images"
collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: "{{year}}-{{month}}-{{day}} • {{title}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Run Date", name: "date", widget: "datetime" }
      - { label: "Runner Name", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Run Time", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
